name: 'AWS CDK Action'
description: 'Run AWS CDK Commands'
inputs:
  cdk_version:  
    description: 'Version of AWS CDK to install'
    required: false
    default: 'latest'
outputs:
  status_code:
    description: 'Status code of AWS CDK CLI'
runs:
  using: 'node12'
  main: 'dist/index.js'
