name: 'AWS CDK Action'
description: 'Run AWS CDK Commands'
inputs:
  cdk_command:
    description: 'CDK Command to execute'
    required: true
  cdk_args:
    description: 'Arguments for CDK Command'
    required: false
    default: ''
  working_dir:
    description: 'AWS CDK Working Directory'
    required: false
    default: '.'
  cdk_version:  
    description: 'Version of AWS CDK to install'
    required: false
    default: 'latest'
  cdk_language:
    description: 'Language for the CDK project'
    required: false
    default: 'typescript'
  pr_comments:
    description: 'If enabled CDK output will be on PR Comment for PRs'
    required: false
    default: true
outputs:
  exit_code:
    description: 'Exit code of AWS CDK CLI'
runs:
  using: 'node12'
  main: 'dist/index.js'
