name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      cdk_version:
        type: choice
        description: 'Version of CDK to Install'
        options:
          - 'latest'
          - '2.2.0'
        required: false
        default: 'latest'
      cdk_command:
        type: choice
        description: 'CDK Command to execute'
        required: false
        default: 'help'
        options:
          - 'help'
          - 'version'

jobs:
  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
    - uses: actions/checkout@v3.1.0
    - uses: ./
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        cdk_command: 'help'
        pr_comments: true