name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      cdk_version:
        type: choice
        description: 'Version of CDK to Install'
        options:
          - 'latest'
          - '2.2.0'
        required: false
        default: 'latest'
      cdk_command:
        type: choice
        description: 'CDK Command to execute'
        required: false
        default: 'help'
        options:
          - 'help'
          - 'version'

jobs:
  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        cdk_version: '2.2.0'
        cdk_command: 'help'        
